/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exchange single-use launch code for session cookie, then redirect to UI */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to `/` with Set-Cookie `session` (HttpOnly; SameSite=Strict) */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Code invalid, used or expired */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and app info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "ok",
                         *       "version": "1.0.0",
                         *       "mode": "mock"
                         *     }
                         */
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current sign-in and data state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "mode": "mock",
                         *       "signed_in": true,
                         *       "user_display_name": "Demo User",
                         *       "source_name": "Mock iManage",
                         *       "has_data": true,
                         *       "last_sync_at": "2026-10-06T21:00:00Z",
                         *       "coverage": {
                         *         "libraries": 1,
                         *         "workspaces_visible": 412,
                         *         "documents": 38410
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start delegated sign-in to the DMS (live mode). In mock mode completes immediately. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sign-in started or completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignInStart"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove DMS tokens from Credential Manager. Local data is kept. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest or running sync */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "state": "idle",
                         *       "current": null,
                         *       "last": {
                         *         "id": "run_01",
                         *         "kind": "incremental",
                         *         "status": "succeeded",
                         *         "started_at": "2026-10-06T20:55:00Z",
                         *         "finished_at": "2026-10-06T21:00:00Z",
                         *         "workspaces_done": 412,
                         *         "workspaces_total": 412,
                         *         "documents_seen": 1203,
                         *         "error": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["SyncStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @default auto
                         * @enum {string}
                         */
                        kind?: "auto" | "full" | "reconcile";
                    };
                };
            };
            responses: {
                /** @description Sync started */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facet values for filter dropdowns */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "practice_areas": [
                         *         "Corporate",
                         *         "Litigation",
                         *         "Property"
                         *       ],
                         *       "partners": [
                         *         {
                         *           "id": "p01",
                         *           "name": "Partner Alpha"
                         *         }
                         *       ],
                         *       "fee_earners": [
                         *         {
                         *           "id": "f01",
                         *           "name": "Fee Earner One"
                         *         }
                         *       ],
                         *       "offices": [
                         *         "Dublin",
                         *         "Limerick"
                         *       ],
                         *       "opened_range": {
                         *         "min": "2019-01-03",
                         *         "max": "2026-10-05"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Filters"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Control definitions (from controls.yaml) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "EL1",
                         *         "name": "Engagement letter / s.150 notice",
                         *         "category": "engagement",
                         *         "description": "Engagement letter or s.150 notice filed within 14 days of first substantive document.",
                         *         "severity": 3,
                         *         "basis": "imanage_filing",
                         *         "configured": true
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["ControlDef"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    practice_area?: components["parameters"]["PracticeArea"];
                    partner_id?: components["parameters"]["Partner"];
                    fee_earner_id?: components["parameters"]["FeeEarner"];
                    office?: components["parameters"]["Office"];
                    status?: components["parameters"]["MatterStatus"];
                    opened_from?: components["parameters"]["OpenedFrom"];
                    opened_to?: components["parameters"]["OpenedTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Headline portfolio metrics for the filtered scope */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "scope": {
                         *         "matters": 412,
                         *         "open_matters": 287
                         *       },
                         *       "readiness": 78.4,
                         *       "high_risk_matters": 23,
                         *       "exceptions_open": 311,
                         *       "upcoming_key_dates": {
                         *         "d30": 6,
                         *         "d60": 11,
                         *         "d90": 19
                         *       },
                         *       "controls": [
                         *         {
                         *           "control_id": "EL1",
                         *           "applicable": 398,
                         *           "pass": 341,
                         *           "late": 31,
                         *           "missing": 22,
                         *           "stale": 0,
                         *           "pending": 4,
                         *           "not_applicable": 0,
                         *           "unknown": 0,
                         *           "compliance_rate": 0.866
                         *         }
                         *       ],
                         *       "coverage_note": "Based on 412 workspaces visible to you in 1 library."
                         *     }
                         */
                        "application/json": components["schemas"]["PortfolioSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compliance rate per control sliced by a dimension (heatmap data) */
        get: {
            parameters: {
                query: {
                    dimension: "practice_area" | "partner" | "fee_earner" | "office" | "opened_month";
                    practice_area?: components["parameters"]["PracticeArea"];
                    partner_id?: components["parameters"]["Partner"];
                    fee_earner_id?: components["parameters"]["FeeEarner"];
                    office?: components["parameters"]["Office"];
                    status?: components["parameters"]["MatterStatus"];
                    opened_from?: components["parameters"]["OpenedFrom"];
                    opened_to?: components["parameters"]["OpenedTo"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "dimension": "practice_area",
                         *       "rows": [
                         *         {
                         *           "key": "Corporate",
                         *           "label": "Corporate",
                         *           "matters": 120,
                         *           "readiness": 81.2,
                         *           "cells": [
                         *             {
                         *               "control_id": "EL1",
                         *               "applicable": 118,
                         *               "passing": 104,
                         *               "compliance_rate": 0.881
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["Breakdown"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness / control compliance over time from snapshots */
        get: {
            parameters: {
                query?: {
                    /** @description Omit or `ALL` for overall readiness */
                    control_id?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "control_id": "ALL",
                         *       "points": [
                         *         {
                         *           "taken_at": "2026-09-01T00:00:00Z",
                         *           "applicable": 4010,
                         *           "passing": 3100,
                         *           "value": 77.3
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["Trend"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /** @description Free text over client/matter code and name */
                    q?: string;
                    practice_area?: components["parameters"]["PracticeArea"];
                    partner_id?: components["parameters"]["Partner"];
                    fee_earner_id?: components["parameters"]["FeeEarner"];
                    office?: components["parameters"]["Office"];
                    status?: components["parameters"]["MatterStatus"];
                    opened_from?: components["parameters"]["OpenedFrom"];
                    opened_to?: components["parameters"]["OpenedTo"];
                    /** @description Only matters where this control is late/missing/stale */
                    failing_control?: string;
                    min_risk?: number;
                    sort?: "risk_desc" | "risk_asc" | "opened_desc" | "opened_asc" | "activity_desc" | "activity_asc" | "matter_code";
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "total": 1,
                         *       "page": 1,
                         *       "page_size": 50,
                         *       "items": [
                         *         {
                         *           "id": "MOCK!ws-0001",
                         *           "client_code": "C10001",
                         *           "client_name": "Example Holdings Ltd (fictional)",
                         *           "matter_code": "C10001-0001",
                         *           "matter_name": "Share purchase (fictional)",
                         *           "practice_area": "Corporate",
                         *           "partner": {
                         *             "id": "p01",
                         *             "name": "Partner Alpha"
                         *           },
                         *           "fee_earner": {
                         *             "id": "f01",
                         *             "name": "Fee Earner One"
                         *           },
                         *           "office": "Dublin",
                         *           "status": "open",
                         *           "opened_at": "2025-02-11T09:00:00Z",
                         *           "last_activity_at": "2026-09-30T15:12:00Z",
                         *           "doc_count": 214,
                         *           "risk_score": 42.9,
                         *           "failing_controls": [
                         *             "EL2",
                         *             "AN1"
                         *           ],
                         *           "key_date": "2026-11-02"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["MatterPage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    matter_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatterDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flat list of failing control results (late/missing/stale) */
        get: {
            parameters: {
                query?: {
                    control_id?: string;
                    status?: "late" | "missing" | "stale";
                    practice_area?: components["parameters"]["PracticeArea"];
                    partner_id?: components["parameters"]["Partner"];
                    fee_earner_id?: components["parameters"]["FeeEarner"];
                    office?: components["parameters"]["Office"];
                    sort?: "severity_desc" | "days_late_desc" | "opened_desc";
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExceptionPage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/key-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matters with a mapped key date in the next N days */
        get: {
            parameters: {
                query?: {
                    within_days?: 30 | 60 | 90;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KeyDate"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lexcel/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reproducible risk-weighted file-review sample */
        get: {
            parameters: {
                query?: {
                    per_fee_earner?: number;
                    /** @description Omit to generate a new seed (returned in response) */
                    seed?: number;
                    practice_area?: components["parameters"]["PracticeArea"];
                    office?: components["parameters"]["Office"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LexcelSample"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "retention_days": 30,
                         *       "sample_per_fee_earner": 2,
                         *       "controls_file": "%APPDATA%\\BWS\\DmsAnalytics\\controls.yaml",
                         *       "controls_loaded_at": "2026-10-06T21:00:00Z"
                         *     }
                         */
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsUpdate"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all local data and the database key. Requires confirm=true. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @constant */
                        confirm: true;
                    };
                };
            };
            responses: {
                /** @description Wiped */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @example sync_running
             * @example not_found
             * @example invalid_request
             * @example not_signed_in
             */
            code: string;
            /** @description Plain-English */
            message: string;
        };
        Health: {
            /** @constant */
            status: "ok";
            version: string;
            /** @enum {string} */
            mode: "mock" | "live";
        };
        Coverage: {
            libraries: number;
            workspaces_visible: number;
            documents: number;
        };
        Session: {
            /** @enum {string} */
            mode: "mock" | "live";
            signed_in: boolean;
            user_display_name?: string | null;
            source_name?: string;
            has_data: boolean;
            /** Format: date-time */
            last_sync_at?: string | null;
            coverage: components["schemas"]["Coverage"];
        };
        SignInStart: {
            /** @enum {string} */
            status: "browser_opened" | "device_code" | "signed_in";
            verification_url?: string | null;
            user_code?: string | null;
        };
        SyncRun: {
            id: string;
            /** @enum {string} */
            kind: "full" | "incremental" | "reconcile";
            /** @enum {string} */
            status: "running" | "succeeded" | "failed" | "cancelled";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            workspaces_done: number;
            workspaces_total?: number | null;
            documents_seen: number;
            error?: string | null;
        };
        SyncStatus: {
            /** @enum {string} */
            state: "idle" | "running" | "cancelling";
            current?: components["schemas"]["SyncRun"] | null;
            last?: components["schemas"]["SyncRun"] | null;
        };
        PersonRef: {
            id: string;
            name: string;
        };
        Filters: {
            practice_areas: string[];
            partners: components["schemas"]["PersonRef"][];
            fee_earners: components["schemas"]["PersonRef"][];
            offices: string[];
            opened_range?: {
                /** Format: date */
                min?: string | null;
                /** Format: date */
                max?: string | null;
            };
        };
        ControlDef: {
            id: string;
            name: string;
            /** @enum {string} */
            category: "file_opening" | "conflicts" | "aml" | "engagement" | "attendance" | "critical_dates" | "fees" | "hygiene";
            description: string;
            severity: number;
            /** @enum {string} */
            basis: "imanage_filing";
            /** @description false when mapping is missing so all results are `unknown` */
            configured: boolean;
        };
        /** @enum {string} */
        ControlStatus: "pass" | "late" | "missing" | "stale" | "pending" | "not_applicable" | "unknown";
        ControlTally: {
            control_id: string;
            /** @description pass+late+missing+stale+pending */
            applicable: number;
            pass: number;
            late: number;
            missing: number;
            stale: number;
            pending: number;
            not_applicable: number;
            unknown: number;
            /** @description pass/(pass+late+missing+stale); null if denominator 0 */
            compliance_rate: number | null;
        };
        PortfolioSummary: {
            scope: {
                matters: number;
                open_matters: number;
            };
            /** @description Mean matter readiness 0-100 */
            readiness: number | null;
            /** @description risk_score >= 50 */
            high_risk_matters: number;
            exceptions_open: number;
            upcoming_key_dates: {
                d30: number;
                d60: number;
                d90: number;
            };
            controls: components["schemas"]["ControlTally"][];
            coverage_note: string;
        };
        BreakdownCell: {
            control_id: string;
            applicable: number;
            passing: number;
            compliance_rate: number | null;
        };
        Breakdown: {
            dimension: string;
            rows: {
                key: string;
                label: string;
                matters: number;
                readiness: number | null;
                cells: components["schemas"]["BreakdownCell"][];
            }[];
        };
        Trend: {
            control_id: string;
            points: {
                /** Format: date-time */
                taken_at: string;
                applicable: number;
                passing: number;
                /** @description Readiness (ALL) or compliance % (0-100) */
                value: number | null;
            }[];
        };
        MatterSummary: {
            id: string;
            client_code: string;
            client_name: string;
            matter_code: string;
            matter_name: string;
            practice_area: string | null;
            partner: components["schemas"]["PersonRef"] | null;
            fee_earner: components["schemas"]["PersonRef"] | null;
            office: string | null;
            /** @enum {string} */
            status: "open" | "closed";
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            last_activity_at: string | null;
            doc_count: number;
            risk_score: number | null;
            failing_controls: string[];
            /** Format: date */
            key_date: string | null;
        };
        MatterPage: {
            total: number;
            page: number;
            page_size: number;
            items: components["schemas"]["MatterSummary"][];
        };
        EvidenceDoc: {
            id: string;
            name: string;
            canonical_type: string | null;
            /** Format: date-time */
            filed_at: string;
        };
        ControlResult: {
            control_id: string;
            status: components["schemas"]["ControlStatus"];
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            evidence_at?: string | null;
            days_late?: number | null;
            /** @description Plain-English reason */
            explanation?: string;
            evidence?: components["schemas"]["EvidenceDoc"][];
            /** @enum {string} */
            basis: "imanage_filing";
        };
        MatterDetail: components["schemas"]["MatterSummary"] & {
            controls: components["schemas"]["ControlResult"][];
            /** @description Key filing events, chronological */
            timeline: {
                /** Format: date-time */
                at: string;
                /** @enum {string} */
                kind: "opened" | "first_substantive" | "evidence" | "key_date" | "last_activity";
                label: string;
                control_id?: string | null;
            }[];
            doc_type_counts: {
                /** @description null = unmapped/other */
                canonical_type: string | null;
                count: number;
            }[];
        };
        ExceptionItem: {
            matter: components["schemas"]["MatterSummary"];
            control_id: string;
            /** @enum {string} */
            status: "late" | "missing" | "stale";
            severity: number;
            days_late?: number | null;
            /** Format: date-time */
            due_at?: string | null;
            explanation: string;
        };
        ExceptionPage: {
            total: number;
            page: number;
            page_size: number;
            items: components["schemas"]["ExceptionItem"][];
        };
        KeyDate: {
            matter: components["schemas"]["MatterSummary"];
            /** Format: date */
            key_date: string;
            days_until: number;
        };
        LexcelSample: {
            seed: number;
            per_fee_earner: number;
            /** Format: date-time */
            generated_at: string;
            items: {
                fee_earner: components["schemas"]["PersonRef"];
                matters: components["schemas"]["MatterSummary"][];
            }[];
        };
        Settings: {
            retention_days: number;
            sample_per_fee_earner: number;
            controls_file: string;
            /** Format: date-time */
            controls_loaded_at: string | null;
        };
        SettingsUpdate: {
            retention_days?: number;
            sample_per_fee_earner?: number;
        };
    };
    responses: {
        /** @description Missing/invalid session cookie or header */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PracticeArea: string;
        Partner: string;
        FeeEarner: string;
        Office: string;
        MatterStatus: "open" | "closed" | "all";
        OpenedFrom: string;
        OpenedTo: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
